apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        flush     1
        log_level info

    [INPUT]
        name      dummy
        dummy     {"name": "Fluent Bit", "year": 2020}
        samples   1
        tag       var.log.containers.app-default-96cbdef2340.log

    [OUTPUT]
        name                  azure_blob
        match                 *
        account_name          fdada
        shared_key            your-storage-account-key
        path                  kubernetes
        container_name        logs
        auto_create_container on
        tls                   on